Fixed an issue where the converter would generate duplicate key names in the "Entries" dictionary.
AnotherPillow/CPA2SC pull request #4
Opened 2024-11-08 12:42 UTC by tiehu

Fixes #3 : This PR updates the key naming logic in the converter to include `LogName`, preventing duplicate keys in the `Entries` dictionary.

2024-11-09 17:37 UTC, AnotherPillow requested changes
This will error if there's no LogName field

2024-11-09 18:00 UTC, tiehu commented
> This will error if there's no LogName field

I don't think this is going to happen, because CP-A forces developers to specify a unique LogName for each patch, otherwise the animation will not load and output the following error in the console:
`[Content Patcher Animations] Animated patches must specify a LogName!`
This point is also mentioned in the CP-A [document](https://github.com/spacechase0/StardewValleyMods/tree/develop/ContentPatcherAnimations):
`Give the patch a unique LogName value.`

2024-11-10 10:45 UTC, tiehu commented
I added a new feature along the way:
The converter now automatically adds `Space Core` as a dependency to `manifest.json`. And users can enter the author name and minimum version of `Space Core` themselves (the default value is used if left blank).

2024-11-12 18:46 UTC, AnotherPillow reviewed
Spacecore dependency adding great, but as a general "rule" I just let the user edit the manifest if they want. Also means that headless usage is easy.

2024-11-12 19:00 UTC, tiehu commented
> Spacecore dependency adding great, but as a general "rule" I just let the user edit the manifest if they want. Also means that headless usage is easy.

Alright, I've rolled back that change.

2025-01-31 18:17 UTC, merged

2025-01-31 18:17 UTC, AnotherPillow commented
yep looks good, will probably just hash logname to prevent any possible weirdness